import { Product } from "@/types/product";

export const products: Product[] = [
  {
    slug: "sapateira-multiuso-compacta-5-prateleiras",
    name: "Sapateira Multiuso Compacta 5 Prateleiras",
    shortDescription: "Organiza até 15 pares em pouco espaço, com montagem simples.",
    description:
      "Sapateira compacta com 5 prateleiras ajustáveis, ideal para corredores e quartos pequenos. Estrutura reforçada e acabamento fosco que combina com qualquer decoração.",
    features: [
      "Até 15 pares de calçados",
      "Prateleiras com altura ajustável",
      "Estrutura em aço com pintura eletrostática",
      "Montagem sem ferramentas especiais",
    ],
    price: 349.9,
    installments: 12,
    category: "organizadores",
    accent: "#FAAA6E",
    dimensions: "70cm (L) x 90cm (A) x 28cm (P)",
    material: "Aço com pintura eletrostática",
    availability: "in_stock",
    sku: "JL-SMC-001",
  },
  {
    slug: "rack-baixo-tv-linha-ipe",
    name: "Rack Baixo para TV Linha Ipê",
    shortDescription: "Rack baixo com dois nichos e acabamento amadeirado.",
    description:
      "Rack para TVs de até 55'', com dois compartimentos abertos para organizar acessórios e um design baixo que valoriza salas pequenas e grandes.",
    features: [
      "Compatível com TVs de até 55''",
      "2 nichos abertos + 1 porta",
      "Painel amadeirado resistente a manchas",
      "Passa-cabos traseiro embutido",
    ],
    price: 599.9,
    installments: 12,
    category: "sala",
    accent: "#141F2D",
    dimensions: "140cm (L) x 40cm (A) x 35cm (P)",
    material: "MDP amadeirado 15mm",
    availability: "in_stock",
    sku: "JL-RBT-002",
  },
  {
    slug: "estante-modular-escritorio-3-nichos",
    name: "Estante Modular Escritório 3 Nichos",
    shortDescription: "Estante vertical para livros, papéis e decoração.",
    description:
      "Estante modular com 3 nichos independentes, perfeita para home office. Estrutura leve, mas resistente, que aproveita bem o espaço vertical do ambiente.",
    features: [
      "3 nichos independentes",
      "Suporta até 8kg por nicho",
      "Fixação na parede incluída",
      "Acabamento em laca fosca",
    ],
    price: 429.9,
    installments: 12,
    category: "escritorio",
    accent: "#B47A4F",
    dimensions: "60cm (L) x 120cm (A) x 25cm (P)",
    material: "MDF laqueado",
    availability: "in_stock",
    sku: "JL-EME-003",
  },
  {
    slug: "comoda-multifuncional-quarto-compacta",
    name: "Cômoda Multifuncional Quarto Compacta",
    shortDescription: "4 gavetas com corrediças reforçadas para o quarto.",
    description:
      "Cômoda compacta com 4 gavetas amplas, ideal para quartos de casal ou solteiro. Corrediças reforçadas garantem abertura suave mesmo com peso.",
    features: [
      "4 gavetas amplas",
      "Corrediças reforçadas",
      "Puxadores em metal escovado",
      "Pés emborrachados antiderrapantes",
    ],
    price: 689.9,
    installments: 12,
    category: "quarto",
    accent: "#FAAA6E",
    dimensions: "80cm (L) x 75cm (A) x 40cm (P)",
    material: "MDP com puxadores em metal",
    availability: "in_stock",
    sku: "JL-CMQ-004",
  },
  {
    slug: "carrinho-organizador-cozinha-3-andares",
    name: "Carrinho Organizador de Cozinha 3 Andares",
    shortDescription: "Carrinho com rodinhas para otimizar a cozinha.",
    description:
      "Carrinho organizador com 3 andares e rodízios, perfeito para armazenar temperos, potes e utensílios. Fácil de mover para limpeza ou uso em outros ambientes.",
    features: [
      "3 andares com bordas de proteção",
      "Rodízios com trava de segurança",
      "Estrutura em aço inox escovado",
      "Suporta até 5kg por andar",
    ],
    price: 249.9,
    installments: 12,
    category: "cozinha",
    accent: "#141F2D",
    dimensions: "35cm (L) x 82cm (A) x 40cm (P)",
    material: "Aço inox escovado",
    availability: "in_stock",
    sku: "JL-COC-005",
  },
  {
    slug: "painel-organizador-parede-ganchos",
    name: "Painel Organizador de Parede com Ganchos",
    shortDescription: "Painel vertical com ganchos para utensílios e acessórios.",
    description:
      "Painel para fixar na parede com 8 ganchos removíveis, ótimo para cozinhas, lavanderias ou ateliês. Aproveita o espaço vertical sem ocupar o chão.",
    features: [
      "8 ganchos removíveis inclusos",
      "Suporta até 3kg por gancho",
      "Fixação com parafusos inclusos",
      "Acabamento resistente à umidade",
    ],
    price: 179.9,
    installments: 12,
    category: "area-de-servico",
    accent: "#B47A4F",
    dimensions: "60cm (L) x 40cm (A)",
    material: "Aço galvanizado pintado",
    availability: "in_stock",
    sku: "JL-POP-006",
  },
  {
    slug: "mesa-dobravel-parede-multiuso",
    name: "Mesa Dobrável de Parede Multiuso",
    shortDescription: "Mesa que dobra e recolhe na parede, ideal para espaços pequenos.",
    description:
      "Mesa fixada na parede com sistema de dobradiça reforçada: desce para uso e recolhe na vertical quando não está em uso. Ótima para cozinhas compactas, lavanderias ou home office improvisado.",
    features: [
      "Tampo de 80cm x 50cm quando aberta",
      "Dobradiças com trava de segurança",
      "Suporta até 15kg em uso",
      "Kit de fixação incluso",
    ],
    price: 259.9,
    installments: 12,
    category: "cozinha",
    accent: "#FAAA6E",
    dimensions: "80cm (L) x 50cm (P) aberta · 8cm (P) fechada",
    material: "MDP revestido",
    availability: "in_stock",
    sku: "JL-MDP-007",
  },
  {
    slug: "armario-multiuso-area-servico",
    name: "Armário Multiuso Área de Serviço",
    shortDescription: "Armário alto com portas para produtos de limpeza.",
    description:
      "Armário alto com 2 portas e 3 prateleiras internas, pensado para áreas de serviço e lavanderias. Organiza produtos de limpeza fora do alcance de crianças pequenas.",
    features: [
      "2 portas com fechamento magnético",
      "3 prateleiras internas ajustáveis",
      "Trava de segurança incluída",
      "Base reforçada contra umidade",
    ],
    price: 749.9,
    installments: 12,
    category: "area-de-servico",
    accent: "#141F2D",
    dimensions: "80cm (L) x 180cm (A) x 45cm (P)",
    material: "MDP hidrofugado",
    availability: "in_stock",
    sku: "JL-AMA-008",
  },
  {
    slug: "kit-organizador-empilhavel-armario",
    name: "Kit Organizador Empilhável para Armário (3 peças)",
    shortDescription: "Bandejas empilháveis para aproveitar melhor armários e despensas.",
    description:
      "Kit com 3 bandejas empilháveis, perfeitas para organizar potes, temperos e utensílios em armários de cozinha ou banheiro. Encaixam uma sobre a outra, multiplicando o espaço de armazenamento sem ocupar mais área.",
    features: [
      "3 bandejas empilháveis inclusas",
      "Material atóxico, resistente a altas temperaturas",
      "Encaixe sem parafusos ou ferramentas",
      "Fácil de higienizar",
    ],
    price: 89.9,
    installments: 3,
    category: "cozinha",
    accent: "#B47A4F",
    dimensions: "38cm (L) x 25,5cm (P) x 5cm (A) cada bandeja",
    material: "Polipropileno atóxico",
    availability: "in_stock",
    sku: "JL-KOE-009",
  },
  {
    slug: "cabideiro-multiuso-chao-rodizios",
    name: "Cabideiro Multiuso de Chão com Rodízios",
    shortDescription: "Arara para roupas com rodízios, fácil de mover entre ambientes.",
    description:
      "Cabideiro de chão com barra reforçada e rodízios com trava, ideal para lavanderias, closets ou quartos sem armário suficiente. Prateleira inferior aproveita espaço extra para calçados ou cestos.",
    features: [
      "Barra para até 25 peças de roupa",
      "Rodízios com trava de segurança",
      "Prateleira inferior para calçados/cestos",
      "Estrutura tubular reforçada",
    ],
    price: 299.9,
    installments: 12,
    category: "quarto",
    accent: "#141F2D",
    dimensions: "90cm (L) x 165cm (A) x 45cm (P)",
    material: "Aço tubular cromado",
    availability: "in_stock",
    sku: "JL-CMC-010",
  },
  {
    slug: "nicho-organizador-modular-6-nichos",
    name: "Nicho Organizador Modular 6 Nichos",
    shortDescription: "Estante em cubos para livros, decoração ou roupas.",
    description:
      "Estante modular com 6 nichos quadrados, versátil para sala, quarto infantil ou home office. Pode ser usada na horizontal ou vertical, de acordo com o espaço disponível.",
    features: [
      "6 nichos de 30cm x 30cm",
      "Pode ser montada na horizontal ou vertical",
      "Suporta até 6kg por nicho",
      "Acabamento fosco antirrisco",
    ],
    price: 389.9,
    installments: 12,
    category: "sala",
    accent: "#FAAA6E",
    dimensions: "90cm (L) x 90cm (A) x 30cm (P)",
    material: "MDP com acabamento fosco",
    availability: "in_stock",
    sku: "JL-NOM-011",
  },
  {
    slug: "kit-prateleiras-flutuantes-invisiveis",
    name: "Kit Prateleiras Flutuantes Invisíveis (2 unidades)",
    shortDescription: "Prateleiras com suporte oculto, efeito \"flutuante\" na parede.",
    description:
      "Kit com 2 prateleiras e sistema de suporte oculto, que cria um efeito visual de peças flutuando na parede. Ótimas para exibir livros, plantas ou objetos de decoração sem poluir o ambiente.",
    features: [
      "2 prateleiras de 60cm inclusas",
      "Suporte oculto (fixação interna)",
      "Suporta até 8kg por prateleira",
      "Kit de fixação e nível incluso",
    ],
    price: 139.9,
    installments: 6,
    category: "sala",
    accent: "#B47A4F",
    dimensions: "60cm (L) x 15cm (P) x 4cm (A) cada",
    material: "MDF laqueado com suporte em aço",
    availability: "in_stock",
    sku: "JL-KPF-012",
  },
  {
    slug: "rechaud-inox-retangular-buffet",
    name: "Rechaud Retangular em Aço Inox para Buffet",
    shortDescription:
      "Mantém alimentos aquecidos durante festas e eventos, com cuba removível para higienização.",
    description:
      "Rechaud retangular em aço inox, ideal para manter pratos aquecidos em festas, casamentos e eventos corporativos. Estrutura estável com reservatório para água (banho-maria) e suporte para combustível em gel (não incluso). Cuba removível facilita a limpeza após o uso.",
    features: [
      "Estrutura em aço inox espelhado",
      "Cuba removível para facilitar a higienização",
      "Suporte para combustível em gel (não incluso)",
      "Ideal para bufês, festas e eventos corporativos",
    ],
    price: 149.9,
    installments: 6,
    category: "cozinha",
    accent: "#FAAA6E",
    dimensions: "60cm (C) x 30cm (L) x 25cm (A)",
    material: "Aço inoxidável",
    availability: "in_stock",
    sku: "JL-RIB-013",
  },
  {
    slug: "kit-3-rechauds-redondos-inox",
    name: "Kit 3 Rechauds Redondos em Aço Inox",
    shortDescription:
      "Conjunto com 3 tamanhos para servir porções variadas em festas e eventos.",
    description:
      "Kit com 3 rechauds redondos em aço inox, em tamanhos diferentes, para organizar o buffet de acordo com a quantidade de cada prato. Cubas removíveis e estrutura reforçada, compatíveis com combustível em gel (não incluso).",
    features: [
      "3 rechauds em tamanhos diferentes",
      "Cubas removíveis em aço inox",
      "Compatível com combustível em gel (não incluso)",
      "Indicado para festas, buffets e confraternizações",
    ],
    price: 349.9,
    installments: 10,
    category: "cozinha",
    accent: "#141F2D",
    dimensions: "tamanhos de 20cm, 25cm e 30cm de diâmetro",
    material: "Aço inoxidável",
    availability: "in_stock",
    sku: "JL-KRR-014",
  },
  {
    slug: "lustre-led-teto-redondo-3-tons",
    name: "Lustre de Teto LED Redondo 3 Tons de Luz",
    shortDescription:
      "Luminária de teto com 3 temperaturas de luz ajustáveis por controle remoto.",
    description:
      "Lustre de teto em LED com formato redondo, permitindo alternar entre luz branca quente, neutra e fria conforme o ambiente e o momento do dia. Acompanha controle remoto para ajuste de intensidade. Bivolt (110V/220V). Recomendamos instalação por profissional eletricista qualificado.",
    features: [
      "3 temperaturas de luz: quente, neutra e fria",
      "Controle remoto incluso",
      "Bivolt (110V/220V)",
      "Indicado para salas e quartos de até 15m²",
    ],
    price: 279.9,
    installments: 10,
    category: "iluminacao",
    accent: "#B47A4F",
    dimensions: "40cm de diâmetro x 8cm de altura",
    material: "Acrílico e alumínio",
    availability: "in_stock",
    sku: "JL-LLT-015",
  },
  {
    slug: "kit-acessorios-banheiro-inox-4-pecas",
    name: "Kit Acessórios de Banheiro em Aço Inox (4 peças)",
    shortDescription:
      "Saboneteira, porta-escovas, dispenser e lixeira em aço inox escovado.",
    description:
      "Kit com 4 peças em aço inox escovado para organizar a bancada do banheiro: saboneteira líquida, porta-escovas, dispenser de algodão/cotonetes e lixeira com tampa. Design uniforme que combina com diferentes estilos de decoração.",
    features: [
      "4 peças: saboneteira, porta-escovas, dispenser e lixeira",
      "Acabamento em aço inox escovado",
      "Fácil de limpar e resistente à umidade",
      "Design uniforme para toda a bancada",
    ],
    price: 219.9,
    installments: 8,
    category: "banheiro",
    accent: "#FAAA6E",
    dimensions: "peças variam de 8cm a 22cm de altura",
    material: "Aço inoxidável escovado",
    availability: "in_stock",
    sku: "JL-KAB-016",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
