import type { Product } from "@/types/product";
// deploy-sync: 2026-09-24T15:25-03:00

export const products: Product[] = [
  {
    slug: "sapateira-organizadora-swift-3-gavetas",
    name: "Sapateira Organizadora Niva 3 Gavetas",
    shortDescription:
      "Sapateira slim da Linha Niva, com 3 gavetas basculantes e apenas 14 cm de profundidade.",
    description:
      "A Sapateira Organizadora Niva faz parte da Linha Niva, criada para aproveitar melhor ambientes compactos sem abrir mão de organização e visual clean. Com 67 cm de largura, 110 cm de altura e apenas 14 cm de profundidade, ela se encaixa muito bem em quartos, closets, corredores e halls de entrada. As três gavetas basculantes acomodam até 12 pares de calçados, mantendo tudo protegido e fácil de acessar. O produto é enviado montado e acompanha buchas e parafusos para fixação na parede.",
    features: [
      "Linha Niva — design compacto e funcional",
      "3 gavetas basculantes para até 12 pares — 4 pares por gaveta",
      "Profundidade slim de apenas 14 cm",
      "Produto enviado montado",
      "Fixação na parede com buchas e parafusos inclusos",
      "Ideal para quarto, closet, corredor e hall de entrada",
    ],
    price: 172.9,
    installments: 6,
    category: "organizacao",
    accent: "#141F2D",
    dimensions: "67cm (L) x 110cm (A) x 14cm (P)",
    material: "MDP com acabamento branco",
    availability: "in_stock",
    sku: "JL-SWT-101",
    image: "/produtos/sapateira-niva-produto-01.webp",
    images: [
      "/produtos/sapateira-niva-produto-01.webp",
      "/produtos/sapateira-niva-produto-02.webp",
      "/produtos/sapateira-niva-produto-03.webp",
      "/produtos/sapateira-niva-produto-04.webp",
      "/produtos/sapateira-niva-destaques.webp",
      "/produtos/sapateira-niva-medidas-20260925.webp",
    ],
    imageLabels: [
      "Produto",
      "Gavetas abertas",
      "Vista frontal",
      "Vista lateral",
      "Destaques",
      "Medidas técnicas",
    ],
    collection: "Linha Niva",
  },
  {
    slug: "aparador-niva-89cm-2-portas-mdf",
    name: "Aparador Niva 89cm com 2 Portas em MDF",
    shortDescription:
      "Aparador compacto em MDF com 2 portas, fechamento suave e espaço de apoio para sala, hall ou cantinho do café.",
    description:
      "O Aparador Niva 89cm combina armazenamento fechado e uma superfície ampla de apoio em um móvel compacto. Produzido em MDF, ele pode ser usado como buffet na sala de jantar, apoio no hall de entrada ou base para montar um cantinho do café. As duas portas ajudam a manter louças, xícaras, utensílios e objetos do dia a dia organizados, enquanto a estrutura com visual contemporâneo deixa o ambiente mais leve e funcional.",
    features: [
      "Estrutura 100% MDF com acabamento resistente",
      "2 portas com fechamento suave",
      "Tampo de 89,5 cm para decoração, cafeteira e objetos de apoio",
      "Espaço interno para louças, utensílios e acessórios",
      "Visual contemporâneo com combinação de madeira e estrutura escura",
      "Ideal para sala, hall, cozinha e cantinho do café",
    ],
    price: 244.9,
    installments: 6,
    category: "aparadores",
    accent: "#B47A4F",
    dimensions: "89,5cm (L) x 73cm (A) x 38cm (P)",
    material: "100% MDF com acabamento em pintura UV",
    availability: "in_stock",
    sku: "JL-APN-201",
    image: "/produtos/aparador-niva-produto-01.webp",
    images: [
      "/produtos/aparador-niva-produto-01.webp",
      "/produtos/aparador-niva-produto-02.webp",
      "/produtos/aparador-niva-produto-03.webp",
      "/produtos/aparador-niva-produto-04.webp",
      "/produtos/aparador-niva-destaques.webp",
    ],
    imageLabels: [
      "Produto",
      "Vista adicional 1",
      "Vista adicional 2",
      "Outra opção de acabamento",
      "Destaques",
    ],
    collection: "Linha Niva",
  },
  {
    slug: "estante-niva-73cm-3-prateleiras-2-gavetas",
    name: "Estante Niva 73cm com 3 Prateleiras e 2 Gavetas",
    shortDescription:
      "Estante vertical em MDF com 3 prateleiras abertas, 2 gavetas e corrediças telescópicas.",
    description:
      "A Estante Niva foi pensada para aproveitar o espaço vertical com uma composição leve e funcional. As três prateleiras deixam livros, plantas e objetos decorativos sempre visíveis, enquanto as duas gavetas criam uma área discreta para guardar controles, documentos, cabos e pequenos acessórios. A estrutura em MDF combina acabamento claro com detalhes amadeirados, criando uma peça versátil para sala, escritório ou quarto.",
    features: [
      "Estrutura 100% MDF",
      "3 prateleiras para livros, plantas e decoração",
      "2 gavetas para organização discreta",
      "Corrediças telescópicas para abertura suave",
      "Combinação de acabamento claro, madeira e detalhes metálicos",
      "Ideal para sala, escritório, quarto e home office",
    ],
    price: 342.9,
    installments: 6,
    category: "sala",
    accent: "#ECCEB0",
    dimensions: "73cm (L) x 185cm (A) x 32cm (P)",
    material: "100% MDF",
    availability: "in_stock",
    sku: "JL-ESN-202",
    image: "/produtos/estante-niva-produto-01.webp",
    images: [
      "/produtos/estante-niva-produto-01.webp",
      "/produtos/estante-niva-produto-02.webp",
      "/produtos/estante-niva-produto-03.webp",
      "/produtos/estante-niva-produto-04.webp",
      "/produtos/estante-niva-destaques.webp",
    ],
    imageLabels: [
      "Produto",
      "Vista adicional 1",
      "Vista adicional 2",
      "Vista adicional 3",
      "Destaques",
    ],
    collection: "Linha Niva",
  },
  {
    slug: "cristaleira-niva-53cm-led-porta-vidro",
    name: "Cristaleira Niva 53cm com LED e Porta de Vidro",
    shortDescription:
      "Cristaleira estreita em MDF com iluminação LED, porta de vidro, fundo espelhado e 4 prateleiras de vidro.",
    description:
      "A Cristaleira Niva 53cm foi criada para valorizar taças, copos, louças e objetos decorativos sem ocupar muito espaço. A porta de vidro protege o conteúdo e mantém tudo visível, enquanto o fundo espelhado amplia a sensação de profundidade. A iluminação em LED reforça o efeito de vitrine e as quatro prateleiras de vidro deixam o interior leve e sofisticado. O formato estreito funciona muito bem em salas de jantar, salas de estar e espaços de bar.",
    features: [
      "Iluminação em LED integrada",
      "1 porta de vidro",
      "Fundo espelhado para ampliar o efeito visual",
      "4 prateleiras em vidro",
      "Estrutura em MDF com acabamento resistente",
      "Ideal para taças, copos, louças e objetos decorativos",
    ],
    price: 624.9,
    installments: 6,
    category: "sala",
    accent: "#FAAA6E",
    dimensions: "53cm (L) x 180cm (A) x 35cm (P)",
    material: "MDF, vidro e fundo espelhado",
    availability: "in_stock",
    sku: "JL-CRN-203",
    image: "/produtos/cristaleira-niva-produto-01.webp",
    images: [
      "/produtos/cristaleira-niva-produto-01.webp",
      "/produtos/cristaleira-niva-produto-02.webp",
      "/produtos/cristaleira-niva-produto-03.webp",
      "/produtos/cristaleira-niva-produto-04.webp",
      "/produtos/cristaleira-niva-destaques.webp",
    ],
    imageLabels: [
      "Produto",
      "Vista adicional 1",
      "Vista adicional 2",
      "Enquadramento do produto",
      "Destaques",
    ],
    collection: "Linha Niva",
  },
  {
    slug: "penteadeira-swift-suspensa-60cm",
    name: "Penteadeira Niva Suspensa 60cm em MDF",
    shortDescription:
      "Penteadeira compacta da Linha Niva, com gaveta grande de correr e trilho telescópico.",
    description:
      "A Penteadeira Niva Suspensa 60cm integra a Linha Niva e foi pensada para criar um cantinho de maquiagem funcional mesmo em quartos menores. Produzida em MDF branco, possui uma gaveta grande de correr para organizar maquiagens, perfumes, acessórios e objetos pessoais. O trilho telescópico metálico permite abertura ampla e suave da gaveta, enquanto a instalação suspensa libera o piso e deixa o ambiente visualmente mais leve e fácil de limpar.",
    features: [
      "Linha Niva — visual clean e aproveitamento inteligente do espaço",
      "1 gaveta grande de correr",
      "Trilho telescópico metálico com abertura ampla e suave",
      "Estrutura em MDF branco",
      "Instalação suspensa na parede",
      "Ideal para quarto, closet e cantinho de maquiagem",
    ],
    price: 82.9,
    installments: 6,
    category: "penteadeiras",
    accent: "#FAAA6E",
    dimensions: "60cm (L) x 14cm (A) x 30cm (P)",
    material: "MDF",
    availability: "in_stock",
    sku: "JL-PTS-105",
    image: "/produtos/penteadeira-niva-produto-01.webp",
    images: [
      "/produtos/penteadeira-niva-produto-01.webp",
      "/produtos/penteadeira-niva-produto-02.webp",
      "/produtos/penteadeira-niva-produto-03.webp",
      "/produtos/penteadeira-niva-produto-04.webp",
      "/produtos/penteadeira-niva-destaques.webp",
      "/produtos/penteadeira-niva-medidas.webp",
    ],
    imageLabels: [
      "Produto",
      "Vista frontal",
      "Ambiente",
      "Vista adicional",
      "Destaques",
      "Medidas técnicas",
    ],
    collection: "Linha Niva",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}
