import { Product } from "@/types/product";

export const products: Product[] = [
  {
    slug: "sapateira-multiuso-desmontavel-ref-12225",
    name: "Sapateira Multiuso Desmontável Ref. 12225",
    shortDescription: "Organizador compacto e desmontável para até 12 pares de calçados.",
    description:
      "Sapateira multiuso desmontável com 4 prateleiras, ideal para corredores, quartos e closets pequenos. Estrutura leve, fácil de montar e de guardar quando não estiver em uso.",
    features: [
      "4 prateleiras para até 12 pares de calçados",
      "1 porta com fechamento simples",
      "Estilo minimalista, disponível em cinza, bege ou marrom",
      "Requer montagem — manual incluso",
    ],
    price: 78.9,
    installments: 3,
    category: "organizadores",
    accent: "#FAAA6E",
    dimensions: "35cm (L) x 98cm (A) x 33cm (P)",
    material: "Componentes plásticos e aditivos",
    availability: "in_stock",
    sku: "JL-SMD-101",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_927707-MLA106705394102_022026-E.webp",
  },
  {
    slug: "rack-baixo-tv-retro-2-nichos",
    name: "Rack Baixo para TV Retrô 2 Nichos",
    shortDescription: "Rack baixo com dois nichos abertos e acabamento retrô off white.",
    description:
      "Rack para TV com design retrô e acabamento em pintura UV, que resiste a manchas do dia a dia. Dois nichos abertos ajudam a organizar acessórios sem poluir a sala.",
    features: [
      "2 nichos abertos para organizar acessórios",
      "Acabamento retrô em pintura UV",
      "Estrutura em MDP 15mm resistente a manchas",
      "Requer montagem — manual incluso",
    ],
    price: 500.7,
    installments: 12,
    category: "sala",
    accent: "#141F2D",
    dimensions: "122cm (L) x 64cm (A) x 40cm (P)",
    material: "MDP com pintura UV",
    availability: "in_stock",
    sku: "JL-RTV-102",
    image: "https://http2.mlstatic.com/D_NQ_NP_795758-MLA114640211047_072026-O.webp",
  },
  {
    slug: "estante-biblioteca-modular-5-prateleiras",
    name: "Conjunto de Estantes Modulares 5 Prateleiras",
    shortDescription: "Duas estantes altas com 5 prateleiras cada, ideais para livros e home office.",
    description:
      "Conjunto com duas estantes modulares de 5 prateleiras, perfeitas para organizar livros, papéis e decoração em home office ou sala de estudos. Estrutura em MDP com painel traseiro e divisões internas.",
    features: [
      "5 prateleiras por estante, com divisões internas",
      "Suporta até 15kg por prateleira",
      "Painel traseiro para maior estabilidade",
      "Requer montagem — manual incluso",
    ],
    price: 668.72,
    installments: 12,
    category: "escritorio",
    accent: "#B47A4F",
    dimensions: "70cm (L) x 180cm (A) x 30cm (P) cada estante",
    material: "MDP com pintura UV",
    availability: "in_stock",
    sku: "JL-EBM-103",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_760353-MLA106197430249_012026-E.webp",
  },
  {
    slug: "comoda-4-gavetas-nature",
    name: "Cômoda 4 Gavetas com Sapateira Nature",
    shortDescription: "4 gavetas amplas e sapateira integrada em acabamento nature.",
    description:
      "Cômoda com 4 gavetas e sapateira integrada, ideal para quartos de casal ou solteiro. Corrediças em metal garantem abertura suave mesmo com peso.",
    features: [
      "4 gavetas amplas com corrediças de metal",
      "1 porta com prateleira interna",
      "Pés reforçados",
      "Requer montagem — manual e parafusos inclusos",
    ],
    price: 565.9,
    installments: 12,
    category: "quarto",
    accent: "#FAAA6E",
    dimensions: "105cm (L) x 92cm (A) x 45cm (P)",
    material: "MDP com acabamento UV",
    availability: "in_stock",
    sku: "JL-CGN-104",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_714957-MLA99990526291_112025-E.webp",
  },
  {
    slug: "carrinho-organizador-cozinha-aco-carbono",
    name: "Carrinho Organizador de Cozinha 3 Andares",
    shortDescription: "Carrinho com rodinhas e 3 andares para otimizar a cozinha.",
    description:
      "Carrinho organizador com 3 andares em aço carbono, perfeito para armazenar temperos, potes e utensílios. Alças facilitam mover para limpeza ou uso em outros ambientes.",
    features: [
      "3 andares em aço carbono",
      "Alças para facilitar o transporte",
      "Formato retangular compacto",
      "Fácil montagem",
    ],
    price: 191.18,
    installments: 6,
    category: "cozinha",
    accent: "#141F2D",
    dimensions: "42,5cm (L) x 75,5cm (A) x 30cm (P)",
    material: "Aço carbono",
    availability: "in_stock",
    sku: "JL-COA-105",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_993734-MLA99368316940_112025-E.webp",
  },
  {
    slug: "armario-multiuso-lavanderia-texas",
    name: "Armário Alto Multiuso para Lavanderia Texas",
    shortDescription: "Armário alto com 2 portas e 4 prateleiras para produtos de limpeza.",
    description:
      "Armário alto com 2 portas e 4 prateleiras internas, pensado para áreas de serviço e lavanderias. Organiza produtos de limpeza, vassouras e rodos fora do alcance de crianças pequenas.",
    features: [
      "2 portas e 4 prateleiras internas",
      "Suporte lateral para vassoura e rodo",
      "Suporta até 20kg de carga",
      "Requer montagem — manual incluso",
    ],
    price: 499.05,
    installments: 12,
    category: "area-de-servico",
    accent: "#B47A4F",
    dimensions: "66cm (L) x 171cm (A) x 45cm (P)",
    material: "MDP",
    availability: "in_stock",
    sku: "JL-AML-106",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_722505-MLA109028278355_032026-E.webp",
  },
  {
    slug: "plafon-led-redondo-3-tons-36w",
    name: "Plafon LED Redondo 36W com 3 Tons de Luz",
    shortDescription: "Luminária de teto com 3 temperaturas de luz e acabamento dourado fosco.",
    description:
      "Plafon de teto em LED, formato redondo, com 3 temperaturas de luz (quente, neutra e fria) para se adaptar ao ambiente e ao momento do dia. Bivolt automático (110V/220V). Recomendamos instalação por profissional eletricista qualificado.",
    features: [
      "3 temperaturas de luz: 3000K, 4500K e 6000K",
      "36W de potência, lâmpada LED inclusa",
      "Bivolt automático (110V/220V)",
      "Acabamento em metal e acrílico",
    ],
    price: 269.9,
    installments: 10,
    category: "iluminacao",
    accent: "#FAAA6E",
    dimensions: "34cm de diâmetro x 7cm de altura",
    material: "Metal e acrílico",
    availability: "in_stock",
    sku: "JL-PLR-107",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_644225-MLA113049802635_062026-E.webp",
  },
  {
    slug: "kit-acessorios-banheiro-inox-polido",
    name: "Kit Acessórios de Banheiro em Aço Inox Polido (4 peças)",
    shortDescription: "Kit com 4 peças em aço inox polido para organizar o banheiro.",
    description:
      "Kit com 4 peças em aço inoxidável polido para o banheiro, incluindo suporte para toalhas. Acabamento cromado que combina com diferentes estilos de decoração. Acompanha parafusos e buchas para instalação.",
    features: [
      "4 peças em aço inoxidável polido",
      "Acabamento cromado",
      "Suporte para toalhas incluso",
      "Kit de fixação (parafusos e buchas) incluso",
    ],
    price: 190.81,
    installments: 6,
    category: "banheiro",
    accent: "#141F2D",
    dimensions: "60cm (L) x 5cm (A) x 10cm (P)",
    material: "Aço inoxidável",
    availability: "in_stock",
    sku: "JL-KBI-108",
    image: "https://http2.mlstatic.com/D_Q_NP_2X_882559-MLA110688376874_052026-E.webp",
  },
  {
        slug: "sapateira-slim-basculante-3-compartimentos",
        name: "Sapateira Slim Basculante 3 Compartimentos",
        shortDescription:
                "Sapateira suspensa slim com 3 compartimentos basculantes para até 12 pares.",
        description:
                "Organize até 12 pares de sapatos sem tirar nem um centímetro de espaço da sua casa. Com apenas 16 cm de profundidade fechada, essa sapateira suspensa é a solução perfeita para halls de entrada, corredores estreitos e atrás da porta — lugares onde um móvel tradicional simplesmente não cabe. Os 3 compartimentos basculantes abrem com um gesto simples, revelando todos os pares de uma vez, sem precisar empilhar ou remexer. As dobradiças ficam escondidas por dentro, deixando a frente lisa e sem puxadores à vista — um visual limpo que combina com qualquer decoração. Fabricada em MDP branco, a peça já vem montada de fábrica: é só fixar na parede (buchas e parafusos para alvenaria inclusos) e guardar os calçados.",
features: [
  "3 compartimentos basculantes — até 12 pares (4 por gaveta)",
  "Dobradiças internas em polímero, sem puxadores aparentes",
  "Vem montada de fábrica — só fixar na parede (buchas e parafusos inclusos)",
  "Suporta até 6,5 kg por gaveta",
],        
    price: 167.9,
    installments: 5,
    category: "organizadores",
    accent: "#B47A4F",
    dimensions: "81cm (L) x 98cm (A) x 16cm (P)",
    material: "MDP",
    availability: "in_stock",
    sku: "JL-SSB-109",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
